name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened-bug-info
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "A clear and concise description of what the bug is."
      value: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: dropdown
    id: version-vinyl
    attributes:
      label: Version
      description: Which version of the Vinyl theme are you using?
      options:
        - 6.5.0
        - 6.4.5
        - 6.4.4
        - 6.4.3
        - Git revision
      default: 0
    validations:
      required: true
  - type: textarea
    id: version-plasma
    attributes:
      label: Version
      description: Which version of Plasma are you using?
      placeholder: "Plasma 6.5.0"
      value: "Plasma 6.5.0"
    validations:
      required: true
  - type: dropdown
    id: version-qt
    attributes:
      label: Version
      description: Which version of QT are you using?
      options:
        - 6.10
        - 6.9
      default: 0      
    validations:
      required: true
  - type: textarea
    id: what-happened-bug-screenshot
    attributes:
      label: Add screenshot
      description: If applicable add screenshots to help explain the problem.
      placeholder: Tell us what you see!
      value: "If applicable add screenshots to help explain the problem."
    validations:
      required: true
  - type: textarea
    id: distribution
    attributes:
      label: Which distribution are you using ?
      description: Which distribution are you using?
      placeholder: ".e.g Arch Linux"
      value: ".e.g Arch Linux"
    validations:
      required: true
  - type: textarea
    id: color-scheme
    attributes:
      label: Which color-scheme are you using ?
      description: Which color-scheme are you using?
      placeholder: ".e.g. Breeze Dark" 
      value: ".e.g Breeze Dark"
    validations:
      required: true
  - type: dropdown
    id: session
    attributes::
      label: Session
      description: Are you using Wayland / X11 ?
      options:
        - Wayland
        - X11
      default: 0
    validations:
      required: true
  - type: dropdown
    id: fractional-scaling
    description: Fractional scaling in use ?
    options:
      - n
      - y
    default: 0
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Add any other context about the bug here
      description: Add any other context about the bug here
      placeholder: "Additional information"
      value: "Additional information"
    validations:
      required: true